### ISSUE TITLE
Is Julia v1.8 compat requirement too strict?

### ISSUE THREAD

**Issue by navidcy** [natgeo-wong/YangShallowWater.jl#2]
Is this too strict?
https://github.com/natgeo-wong/YangShallowWater.jl/blob/43f2c055d52858b37e2da24ddf24426e2d2bd7c9/Project.toml#L18

Is any of the deps really need 1.8?

If we do need it then the 1.0 should be removed from the tests as it'll fallback to 1.6.5 I think...
https://github.com/natgeo-wong/YangShallowWater.jl/blob/43f2c055d52858b37e2da24ddf24426e2d2bd7c9/.github/workflows/CI.yml#L21

**Comment by natgeo-wong** [comment]
Mmmmm I could bump it down to the LTS version, true.  I'm just not sure if there's going to be a performance gap between the different Julia versions?

**Comment by navidcy** [comment]
Not sure about performance differences myself. Note that the compat requirement is just the bare minimum req.
