### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by navidcy** [natgeo-wong/YangShallowWater.jl#5]
I see we use NCDatasets?

https://github.com/natgeo-wong/YangShallowWater.jl/blob/e17d0506d0290226be5ac2332635da9ad7f9b9f1/Project.toml#L11

Just noting that FourierFlows gives [output functionality](https://fourierflows.github.io/FourierFlowsDocumentation/dev/output/) via JLD2.

**Comment by natgeo-wong** [comment]
I feel that NCDatasets is much more stable than JLD2 (personally speaking), and NetCDF as a file format is much more intuitively used by non-Julia users to analyze the data output as well. This is why I would choose to use NCDatasets.jl over JLD2.

**Comment by navidcy** [comment]
Gotcha!
